### ISSUE TITLE
dark theme yaml: mapping values are not allowed here

### ISSUE THREAD

**Issue by makeflori** [dwainscheeren/dwains-dashboard-addons#130]
My dashboard often loads with an incorrect color setting (like [here ](https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/318)), so I wanted to try the fix with the new theme. So I set everything as described [here](https://github.com/dwainscheeren/dwains-dashboard-addons/tree/master/lovelace_theme/dwains_dark_theme). However, I always get the following error message during the config check:

> Error loading /config/configuration.yaml: mapping values are not allowed here
> in "/config/themes/dwains_dark_theme/dwains_dark_theme.yaml", line 122, column 65

I have not changed anything in the dark theme yaml, but also do not know how to fix the error.

**Comment by LRvdLinden** [comment]
Strange. There is no line 122 in dwains_dark_theme.yaml. Please copy the .yaml again and place it in: Make shure you have created a themes folder in youre config/

After that place the follow line into your configuration.yaml

```yaml
# Core Configuration
default_config:
frontend:
  themes: !include_dir_merge_named themes/
```

end last thing: Reboot HA

**Comment by makeflori** [comment]
> Strange. There is no line 122 in dwains_dark_theme.yaml. Please copy the .yaml again and place it in: Make shure you have created a themes folder in youre config/

Yes, my mistake! I downloaded the yaml with "save link as..." and then i had a yaml with html code. *facepalm*
