### ISSUE TITLE
Viewing errors for Plants & Find My Addons

### ISSUE THREAD

**Issue by rainyvalley** [dwainscheeren/dwains-dashboard-addons#138]
![image](https://user-images.githubusercontent.com/68121220/148107990-138d8c82-f936-4d7c-b583-955c0e4c405d.png)
As you can see in the picture above, instead of using the entire space the card seems to "scrunch" up.

**Comment by dwainscheeren** [comment]
Yeah this is a bug needs to be fixed in next version. In the mean time to fix it by hand yourself:
Add:

`items_classes: 'col-xs-12 col-sm-12 col-md-12 col-lg-12'`

below

`- type: custom:dwains-flexbox-card`

in rooms/room/addon.yaml and 04.more_page_addons.yaml
