### ISSUE TITLE
find_my help on column width

### ISSUE THREAD

**Issue by carfnann** [dwainscheeren/dwains-dashboard-addons#139]
Hey,

I've just implemented the page find_my (by the way congrats for this amazing job), and I have issue to display correctly.
On a small screen (or page size), the display is ok
<img width="688" alt="Capture d’écran 2022-01-05 à 14 06 00" src="https://user-images.githubusercontent.com/30008968/148224946-380e1ec2-1b8d-4430-af1d-cf4eb7036f8e.png">

but on a large screen/page, it doesn't fit the page.

<img width="1650" alt="Capture d’écran 2022-01-05 à 14 06 32" src="https://user-images.githubusercontent.com/30008968/148224968-d3239fc8-4f6b-4cdd-86ad-dcb8a07da516.png">

I have tried to modify the example items_class but nothing is good.
Why the base parameter are not working for me?
`- type: custom:dwains-flexbox-card
  items_classes: 'col-xs-12'
  cards:
    - type: vertical-stack
      item_classes: 'col-xs-12 col-sm-3'`

**Comment by dwainscheeren** [comment]
See #138
