### ISSUE TITLE
3D Printer - what is needed for the secrets?

### ISSUE THREAD

**Issue by jaburges** [dwainscheeren/dwains-dashboard-addons#19]
The rest commands list !secret octoprint_command etc.
Can you confirm what this should be?

**Comment by RubenDijk** [comment]
'http://Octoprint_IP/api/printer/command'
See : https://github.com/RubenDijk/3D-Printer-Creality-Ender-3/blob/master/entities/rest_commands/rest_cmd_ender3.yaml

**Comment by RubenDijk** [comment]
Need to update it to 1.0.1 I'm gonna run an update 1.0.1. Go do my best to do it this week.

**Comment by jaburges** [comment]
ok looks like you added the 'http://xxx.xxx.x.xx/api/system/commands/core/shutdown'
thats the secrets that need adding I didnt see in the docs

`!secret ender3_octoprint_api_shutdown`

secrets.yaml:
```
ender3_octoprint_api_shutdown: http://xxx.xxx.x.xx/api/system/commands/core/shutdown
```

**Comment by RubenDijk** [comment]
it's updated, please close this one
