### ISSUE TITLE
Vacum addon - error '/config/views/partials/heading.yaml'

### ISSUE THREAD

**Issue by lundig** [dwainscheeren/dwains-dashboard-addons#34]
I get the message: 
`[Errno 2] No such file or directory: '/config/views/partials/heading.yaml`

Does this need to be updated to work with 1.4?

**Comment by Klumpke** [comment]
What is your path where you putted the button.yaml and page.yaml file?
It needs to be `dwains-theme\addons\rooms\<your_room>\vacuum\` to work properly

**Comment by lundig** [comment]
That was the problem.
Thanks
