### ISSUE TITLE
Mistake in READMEs

### ISSUE THREAD

**Issue by dimmuboy** [dwainscheeren/dwains-dashboard-addons#42]
In _custom_resources_ example is swapped url and type line.

**Comment by Klumpke** [comment]
In which addon is this?

**Comment by dimmuboy** [comment]
oh I'm sorry, it's calendar addon :)

**Comment by dimmuboy** [comment]
..and in tv-remote too and in config example "room" missing in button_path

**Comment by Klumpke** [comment]
It doesn't matter what you write down first, URL or module.
I can't find any mistake in the config example . Do you have an example?

**Comment by dimmuboy** [comment]
In [tv-remote example](https://github.com/dwainscheeren/dwains-theme-addons/blob/master/rooms/tv-remote/README.md)
`button_path: 'dwains-theme/addons/<your room>/tv-remote/button.yaml'`
correct is 
`button_path: 'dwains-theme/addons/rooms/<your room>/tv-remote/button.yaml'`

**Comment by Klumpke** [comment]
Ah you're right. Thanks for reporting.

Fixed: #43
