### ISSUE TITLE
Vacuum Addon - Problem with Buttons

### ISSUE THREAD

**Issue by Shoomaan** [dwainscheeren/dwains-dashboard-addons#48]
Title is not translated. Buttons are not showing. Did I something wrong or is there an issue?

![image](https://user-images.githubusercontent.com/37193595/86597907-a6a73200-bf9c-11ea-8abc-812a09d19a7f.png)

**Comment by dwainscheeren** [comment]
@Klumpke

**Comment by Klumpke** [comment]
You need to create an dummy input_boolean to let the buttons work.
I will add this to the setup instructions in the next update.
```yaml
input_boolean:
  dummy1:
    initial: off
```

There was an error in the translation during the upload. I will fix this in the next update.
For now you can edit `line 64` of the `page.yaml` to the title you want.

**Comment by Shoomaan** [comment]
Thank you, got it working now.
