### ISSUE TITLE
Docker Monitor in docked HASS

### ISSUE THREAD

**Issue by dimmuboy** [dwainscheeren/dwains-dashboard-addons#53]
How can I use Docker Monitor, when Home Assistant is running in docker?

**Comment by RubenDijk** [comment]
i am not sure, did not test it
Maby you can try to follow this : https://cyberjunky.nl/docker-monitor-sensor-for-home-assistant/

**Comment by dimmuboy** [comment]
Ah okay, my bad. It works with @RubenDijk 's Docker Monitor addon but I needed to add tcp socket in my docker service and user tcp://ip.address:port
