### ISSUE TITLE
Vacuum addon: allow for service data in control

### ISSUE THREAD

**Issue by ishioni** [dwainscheeren/dwains-dashboard-addons#66]
Hi

I'd like to add a "Go to trash bin" in control, but there's no way to add spot_id. Here's how i call the service

```
service: vacuum.send_command
entity_id: vacuum.valetudo
command: go_to
params:
  spot_id: Bin
```

@Klumpke could you add this please?

**Comment by Klumpke** [comment]
I will look into this.
I need to do some redesign in the code to improve the flexibility and implement this request.
